### ISSUE TITLE
Using the "latest" babel preset

### ISSUE THREAD

**Issue by cowwoc** [rollup/rollup-plugin-babel#119]
This configuration:

```
{
	babelrc: false,
	presets: [
		[
			"latest",
			{
				"modules": false
			}
		]
	],
	exclude: 'node_modules/**',
	plugins: [
		"external-helpers"
	]
})
```

fails with: `It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information`

If I replace `latest` with `es2015` the error goes away. Why is that?

**Comment by cowwoc** [comment]
I got further by replacing `"modules": false` with:

```
"es2015": {
	"modules": false
}
```

I no longer get an error from rollup-plugin-babel. Unfortunately, babel isn't transforming the files as I expected. My source-code contains `Object.entries()` which is supposed to get picked up by the `es2017` but it does not in this case. Any ideas?

**Comment by Rich-Harris** [comment]
Not a Babel user so I could have this wrong, but I was under the impression that the `es2017` preset didn't do anything to `Object.entries()`, because it's an environment feature rather than a language feature — in other words you need a polyfill, either [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) or (recommended) individual polyfills for the features you need, e.g. [es-shims/object.entries](https://github.com/es-shims/Object.entries).

**Comment by cowwoc** [comment]
Good catch. This worked for me: http://stackoverflow.com/a/35382020/14731

Thanks for your help.
