### ISSUE TITLE
with gulpfile.babel.js 

### ISSUE THREAD

**Issue by lc60005457** [rollup/rollup-plugin-babel#12]
gulpfile.babel.js need .babelrc

```
{
  "presets": [ "es2015" ]
}
```

But rollup-plugin-babel need

```
{
  "presets": [ "es2015-rollup" ]
}
```

You cannot eat your cake and have it.

**Comment by Rich-Harris** [comment]
You're the one trying to have your cake and eat it! You're trying to use a single configuration file for different tasks.

rollup-plugin-babel allows you to pass in the configuration directly:

```js
import { rollup } from 'rollup';
import babel from 'rollup-plugin-babel';

rollup({
  entry: 'main.js',
  plugins: [
    babel({
      presets: [ 'es2015-rollup' ]
    })
  ]
}).then(...)
```

Unfortunately you can't have that *and* a `.babelrc` file, because the presets get merged and Babel produces borked output (at least, that was the case last time I checked a few days ago). So you need to find a way to pass the correct configuration to Gulp. I'm not a Gulp user so can't help with that I'm afraid.

**Comment by ritz078** [comment]
For someone finding the answer to using both `.babelrc` and this at the same time use

```js
import { rollup } from 'rollup';
import babel from 'rollup-plugin-babel';

rollup({
  entry: 'main.js',
  plugins: [
    babel({
      babelrc:false,
      presets: [ 'es2015-rollup' ]
    })
  ]
}).then(...)
```

**Comment by thisconnect** [comment]
I ran into this too with babel-node cli + .babelrc and another npm script with rollup + npm + babel. I prefer to use rollup with disabled `babelrc: false` and only use babelrc when working with babel directly.

I first thought that merging babelrc was needed when using npm modules with jsnext main, but now the modules that I use distribute transpiled es5 with import export.
