### ISSUE TITLE
Fix error/warnings

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-babel#123]
We can use `this.warn` and `this.error` as of 0.41

* https://github.com/rollup/rollup-plugin-babel/pull/85
* https://github.com/rollup/rollup/issues/1140

**Comment by jharris4** [comment]
Just noticed there's a bug in the warnings for rollup-plugin-label... Was scratching my head because I was seeing warnings like this:

```⚠️   undefined```

I traced it down to the rollup-plugin-babel's warnOnce function, which needs to be changed to the following:

```
function warnOnce ( warn, msg ) {
	if ( warned[ msg ] ) { return; }
	warned[ msg ] = true;
	warn( { message: msg } ); // was previously just warn(msg)
}
```

This is because the default onwarn added by the rollup binary uses the following log function:

```
function log ( object, symbol ) {
	var message = object.plugin ? ("(" + (object.plugin) + " plugin) " + (object.message)) : object.message;
// ....
}
```

I'll look into creating a PR to fix this...
