### ISSUE TITLE
why do I need .babel.rc ?

### ISSUE THREAD

**Issue by yairEO** [rollup/rollup-plugin-babel#14]
when using with Babel 6, the README says you need an `.babel.rc` file set with the right presets, but why can't you just run Babel and just pass the presets directly?

    babel({ presets: ['es2015'] });

**Comment by Rich-Harris** [comment]
You can. The `.babelrc` file is recommended because it's a 'standard' place for different tools to find it, and allows Babel to (for example) use different configuration for different files during the same build. But it's also slightly problematic, because you might want different configuration for different tasks (e.g. the `.babelrc` you need for your gulpfile, or whatever, will likely be different to the configuration you need to create a bundle with Rollup) – so for that reason Rollup allows you to pass in configuration options directly to Babel, exactly as per your snippet.

Be aware that having *both* a `.babelrc` *and* directly passed configuration is likely to summon Zalgo.

**Comment by yairEO** [comment]
Thanks for the quick response!
I followed the guide and installed the `babel-preset-es2015-rollup` package, but it seemed to have ruined my output and is using some helper function which doesn't exist, do you happen to know this issue?

https://github.com/rollup/babel-preset-es2015-rollup/issues/1
