### ISSUE TITLE
Error: Cannot find module '

### ISSUE THREAD

**Issue by negezor** [rollup/rollup-plugin-babel#205]
In my resultant bandle there is now such a require that can not be executed by node.js.
```js
var chalk = _interopDefault(require('chalk'));
var _rollupPluginBabelHelpers = require(' rollupPluginBabelHelpers');
var createDebug = _interopDefault(require('debug'));
```
![image](https://user-images.githubusercontent.com/9392723/38775971-b71ce55a-40da-11e8-8487-385abf719c0a.png)
Rollup config
```js
import json from 'rollup-plugin-json';
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

import nodePath from 'path';

import pkg from './package.json';

const { isAbsolute } = nodePath;

const input = 'src/index.mjs';

export default [
	{
		input,
		external: (id) => {
			if (id === input) {
				return false;
			}

			return !(isAbsolute(id) || id.startsWith('.'));
		},
		plugins: [
			resolve({
				extensions: ['.mjs', '.js'],
				preferBuiltins: true
			}),
			json(),
			babel({
				exclude: [
					'node_modules/**'
				]
			}),
			commonjs()
		],
		output: [
			{
				file: pkg.main,
				format: 'cjs',
				exports: 'named'
			},
			{
				file: pkg.module,
				format: 'es'
			}
		]
	}
];
```
Node: 9.11.0
NPM: 5.6.0
```json
{
  "@babel/core": "^7.0.0-beta.44",
  "@babel/plugin-proposal-object-rest-spread": "^7.0.0-beta.44",
  "@babel/preset-env": "^7.0.0-beta.44",
  "rollup": "^0.57.1",
  "rollup-plugin-babel": "^4.0.0-beta.4",
  "rollup-plugin-commonjs": "^9.1.0",
  "rollup-plugin-json": "^2.3.0",
  "rollup-plugin-node-resolve": "^3.3.0"
}
```

**Comment by CoskunSunali** [comment]
babel plugin seems to be doing interesting stuff here.

I am currently trying to `externalize` the following two modules:

- `rollupPluginBabelHelpers`
- `typescript-helpers`

Using the following code:

```js
        external: (id, parentId, isResolved) => {
            if (id.indexOf('rollupPluginBabelHelpers') > -1) {
                return true;
            } else if (id.indexOf('typescript-helpers') > -1) {
                return true;
            }

            console.log(id);

            return false;
        }
```

And I get the following result: (I cannot even paste the unicode char here, so I will share a screenshot)

![image](https://user-images.githubusercontent.com/6509380/40287294-03e7b892-5cb5-11e8-8415-5c98e3692b1a.png)

It seems similar to the `space` you have in front of `require(' rollupPluginBabelHelpers')`.

**Comment by Andarist** [comment]
It's rollup convention with NUL character, you can read a little bit about it [here](https://github.com/rollup/rollup-plugin-babel/issues/197).

@CoskunSunali Not sure what are you trying to do, could u elaborate?

@negezor you should `return false` for `id` starting with `\0`

**Comment by CoskunSunali** [comment]
@Andarist I gave up using rollup since I concluded that what I need is not bundling but developing modules. However, I will still see how I may explain the issue I had so you might want to fix it in case it is a bug.

I had (still have) a rollup instance running on my project in order to build typescript. I also had to use babel since I needed some features of typescript that needed to be processed via babel in order to get them to work on browsers.

It turned out babel injected plenty of code into every single file that it generated (multiple files because I had the multiEntry plugin utilized), so I wanted it to have those babel helpers of rollup exist in its own system module and not be bundled in every single js file that was generated.

It turns out one way to do so was to mark `rollupPluginBabelHelpers` and `typescript-helpers` as `external` modules within rollup configuration.

My modules still get generated without any issues and as you can see within the screenshot I shared, the modules are not inline anymore and are to be loaded by `System.register`.

That worked syntax wise, the generated files all had the correct output. It was just the modules were not being generated because of some unicode char you can see in front of the module names within the screenshot.

I don't know what else I can provide you with any further but please let me know in case I can.

**Comment by Andarist** [comment]
`rollup` is a very popular choice when it comes to building libraries/modules. Flat bundling is a nice way of reducing your module's size & keeping the structure private (allowing to import only explicit exports). You can read more about it on [react's blog](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#compiling-flat-bundles) and in [my article](https://developers.livechatinc.com/blog/how-to-create-javascript-libraries-in-2018-part-1/).

Problem with `rollupPluginBabelHelpers` is that it is not actual module, it's just created in memory and shouldn't be externalized. 

If you want to keep those helpers external I suggest:
- using properly configured [`@babel/plugin-transform-runtime`](https://babeljs.io/docs/plugins/transform-runtime/) 
- or building (if using babel@7) ur own file of those helpers (u might want to publish it to npm or something) like [here](https://github.com/rollup/rollup-plugin-babel/blob/b05e0ef32903ca4817bef7fe7d9768335a1ae982/src/index.js#L49). Then u could use a copy of [this babel plugin](https://github.com/rollup/rollup-plugin-babel/blob/b05e0ef32903ca4817bef7fe7d9768335a1ae982/src/helperPlugin.js) that would insert appropriate import statements.

As to `typescript-helpers` - you can pass `"importHelpers": true` to `"compilerOptions"`, add `tslib` module as dependency of ur project & keep it as `external`.

**Comment by CoskunSunali** [comment]
> Problem with rollupPluginBabelHelpers is that it is not actual module, it's just created in memory and shouldn't be externalized.

That pretty much explains it. Thanks!

Thanks for the other details too! Very helpful.
