### ISSUE TITLE
Exclude node_modules in yarn workspaces

### ISSUE THREAD

**Issue by donysukardi** [rollup/rollup-plugin-babel#229]
I'm trying to use `rollup-plugin-babel` with yarn workspaces. However I notice that the usual `exclude: 'node_modules/**'` option doesn't seem to catch node_modules that are hoisted to the root of the workspaces, i.e. `../../node_modules`.

```javascript
rollup({
  entry: 'main.js',
  plugins: [
    babel({
      exclude: 'node_modules/**'
    })
  ]
}).then(...)
```

Is there any pattern that I could use that will match all node_modules folders?

**Comment by Andarist** [comment]
I have not tried it, but could u check smth like `**/node_modules/**`?

**Comment by donysukardi** [comment]
Tried that, but it didn’t work. I think it’s an issue with minimatch - https://github.com/isaacs/minimatch/issues/30. There doesn’t seem to be a pattern that could satisfy all paths with node_modules

**Comment by Andarist** [comment]
Actually those patterns are handled by [micromatch](https://github.com/rollup/rollup-pluginutils/blob/a4f039b734e2c119b79e6b67ab588bcc097f7b36/package.json#L33).

Seeing the [source code](https://github.com/rollup/rollup-pluginutils/blob/a4f039b734e2c119b79e6b67ab588bcc097f7b36/src/createFilter.js#L6) it seems that u can actually use RegExp to have better control than with glob patterns. You could also create an issue about this in `rollup-pluginutils` repo, because it seems that this could be supported with glob patterns too.

I think this resolves this issue, but if not please raise ur concerns and I'll reopen.

**Comment by jwineman** [comment]
`rollup-plugin-babel` @ `3.0.7` depends on `rollup-pluginutils`@`^1.5.0` which [doesn't check for `RegExp`](https://github.com/rollup/rollup-pluginutils/blob/v1.5.0/src/createFilter.js#L6). I looks like [the `RegExp` check wasn't added until `2.0.0`](https://github.com/rollup/rollup-pluginutils/blob/v2.0.0/src/createFilter.js).

Since 4.0 is in beta would you accept a PR against 3.x which upgrades `rollup-pluginutils` to `^2.0.0`?

**Comment by Andarist** [comment]
In general I would but the problem is that rollup-pluginutils@2 switched to using micromatch instead of minimatch and while they should be pretty compatible, it's still a breakage risk and I kinda don't have time to check the differences between those 2 and deal with potential problems later. 

You could prepare a PR to current master to support new option - `filter` and backport it to v3 too. That way you could just install `rollup-pluginutils` yourself (in whatever version u like) and create a filtering function urself, which I think would be a nice addition overall.

**Comment by NathanielHill** [comment]
FWIW to anyone looking this works now with `exclude: /node_modules/` :+1: :+1:

**Comment by simkessy** [comment]
@NathanielHill  thanks for an actual answer
