### ISSUE TITLE
Specify a specific `.babelrc`

### ISSUE THREAD

**Issue by mesqueeb** [rollup/rollup-plugin-babel#249]
I have a problem where I need Rollup to specify a .babelrc file inside a `build` dir. Not the nearest .babelrc file to the file it's transpiling, as this causes issues in my setup.

In my case:
- I want to transpile `src/helpers/file.js` with a specific rollup setup and a specific `.babelrc` file.
- `src` gets built through other software also looking for the nearest .babelrc files.
  - this is why I can't put my rollup .babelrc inside `src/helpers` 

Can I specify a .babelrc file inside a specific folder?

**Comment by Andarist** [comment]
Not sure if it's the only option or anything, but u can just use `babelrc: false` and pass any config u want to rollup-plugin-babel.

Smth like
```js
import babel from 'rollup-plugin-babel'
import babelrc from '../../.babelrc.js'

export default {
  input: 'src/helpers/file.js',
  output: { format: 'esm', file: 'build/helpers.js' },
  plugins: [
    babel({
      babelrc: false,
      ...babelrc,
    }),
  ]
}
```

**Comment by loganfsmyth** [comment]
If you're not actually relying on Babel to load your `.babelrc`, I think using the `.babelrc` naming convention is a mistake, since it is now potentially misleading.

Also, if you're on Babel 7.x and you're finding that the file-relative `.babelrc` isn't a good fit for your goal, you can also consider a [project-wide config](http://babeljs.io/docs/en/config-files#project-wide-configuration) or explicitly using the `configFile` option.

**Comment by kopax** [comment]
Where is `configFile` documented In rollup-plugin-babel ? after upgrading I have issue with babel not loading the good presets/plugins.

**Comment by nicolo-ribaudo** [comment]
https://github.com/rollup/rollup-plugin-babel#usage

> All options are as per the Babel documentation, except the following:

From the babel config:

https://babeljs.io/docs/en/options#configfile

**Comment by kopax** [comment]
Thanks, I have found this is not rolated to that module, I have opened another issue [here](https://github.com/rollup/rollup/issues/2597)
