### ISSUE TITLE
babelrc exclude possibly ignored

### ISSUE THREAD

**Issue by zebapy** [rollup/rollup-plugin-babel#269]
I'm using gulp+rollup+rollup babel and importing Swiperjs but have issues when using `.babelrc` vs passing the babel config into `rollupBabel()`

plugins

```js
      plugins: [
        rollupBabel(),
        rollupResolve(),
        rollupCommon(),
        production && uglify()
      ]
```

Swiper offers an esm build so I need babel to transpile it. See https://github.com/nolimits4web/swiper/issues/2602

If this is in a `.babelrc.js` it fails
```js
module.exports = {
  exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
  presets: [
    [
      '@babel/preset-env',
      {
        modules: false
      }
    ]
  ],
  plugins: [
    ['@babel/transform-react-jsx', { pragma: 'h' }],
    '@babel/plugin-proposal-class-properties'
  ]
};

```

gives this error

```bash
class Dom7 {
        |        ^ Unexpected token: name (Dom7)
  10061 |     constructor(arr) {
  10062 |       const self = this; // Create array-like object
  10063 | 
[12:11:40] 'scripts' errored after 5.83 s
[12:11:40] SyntaxError: Unexpected token: name (Dom7)
```

If I put it into babel plugin, it compiles fine

```js
        rollupBabel({
          exclude: /node_modules\/(?!(dom7|ssr-window|swiper)\/).*/,
          presets: [
            [
              '@babel/preset-env',
              {
                modules: false
              }
            ]
          ],
          plugins: [
            ['@babel/transform-react-jsx', { pragma: 'h' }],
            '@babel/plugin-proposal-class-properties'
          ]
        }),
        rollupResolve(),
        rollupCommon(),
        production && uglify()
```

**Comment by Andarist** [comment]
This is probably because babel@7 has changed behaviour in regards to compiling things located in node_modules - also a resolution algorithm for .babelrc files has slightly changed (babelrc files in node_modules wont be found automatically). 

There are various possibilitied how to work around this - one of them is to require your babelrc in rollup.config.js and use its contents as options to rollup-plugin-babel (so a solution similar to what you have done), if you follow that path it's also probably a good idea to use `babelrc: false` option - just to keep a single config (the one passed as options) instead of using it & babelrc files which is harder to reason about. 

Using rollup-plugin-babel options makes the plugins/presets work for all compiled files (according to include/exclude options).
