### ISSUE TITLE
rollup-plugin-babel cannot read .babelrc when run from repo root

### ISSUE THREAD

**Issue by mjackson** [rollup/rollup-plugin-babel#271]
It seems like `rollup-plugin-babel` only finds and reads `.babelrc` files when it is run outside the directory where that package is contained. I am going to post a repro here shortly.

Possibly related to #232, but I'm not sure because the source repo has since been deleted.

**Comment by mjackson** [comment]
OK, repro [is at `mjackson/rollup-plugin-babel-bug`](https://github.com/mjackson/rollup-plugin-babel-bug). If you run that repo, you'll see what I'm talking about.

**Comment by Andarist** [comment]
This is in fact strange and I'm not sure why this happens, however rollup-plugin-babel doesn't load babelrc files on it own - that's babel responsibility, so the issue got kinda reported in the wrong repository.

You can "fix it" by passing `babelrcRoots: ['./packages/*']` as option to you rollup-plugin-babel's instance - it's babel@7 option https://babeljs.io/docs/en/options#babelrcroots .

cc @loganfsmyth

**Comment by loganfsmyth** [comment]
The core of it is that we use the working directory as the default for the `root` package where `.babelrc` are taken into account. There are a few ways to get around that, but since this seems to be a monorepo structure, the standard recommendation is to create a `babel.config.js` in the repo root with `module.exports = { babelrcRoots: ["./packages/*"] };` and then pass `rootMode: "upward"` to the Rollup plugin, since that'll properly load the root config, and the root config will activate `.babelrc` resolution for all monorepo packages. You can also skip the `babel.config.js` and pass that right in the rollup config, but then if you have multiple things that might consume that setting, like Jest or `@babel/register` it can get annoying to repeat the `babelrcRoots` value for each of them.

Probably worth reading through https://babeljs.io/docs/en/config-files though if you have suggestions for improvements, I'm happy to hear them. Realistically, we should have a section specifically about configuring monorepos.

**Comment by mjackson** [comment]
Thanks for taking a look, @Andarist. I think you're right, this is a babel issue. Sorry for filing in the wrong repo.

Thanks for your comment, @loganfsmyth. I read through those docs earlier today, but this part doesn't seem accurate:

> Babel loads .babelrc (and .babelrc.js / package.json#babel) files by searching up the directory structure starting from the "filename" being compiled. This can be powerful because it allows you to create independent configurations for subsections of a repository. 

If that were true, wouldn't the settings in a `.babelrc` file *always* apply to files in that directory or lower, regardless of the current working directory?

For example, in the sample repo I provided the file being compiled is `packages/react-router/modules/index.js`. There is a `.babelrc` at `packages/react-router/modules/.babelrc` that, according to the docs, should be loaded for that file. But it isn't always because it depends on the current working directory. So the docs are a little misleading IMO.

Maybe it's worth mentioning how the current working directory affects the lookup of `.babelrc` files somewhere in those docs?

Thanks again for taking a look.

**Comment by Andarist** [comment]
> Thanks for taking a look, @Andarist. I think you're right, this is a babel issue. Sorry for filing in the wrong repo.

No problem at all.

I definitely agree with @mjackson that current docs around this are misleading - I was reading them while investigating this and couldnt figure out from them what's the exact reason why this babelrc wasnt picked up. I just knew from other issues reported previously how to fix it (with babelrcRoots) but it was unclear for me why it has to be specified in this case.

**Comment by loganfsmyth** [comment]
Yeah you are right that that passage is overly broad. It should probably have a `, subject to the edge cases below.` at the end or something.

**Comment by mjackson** [comment]
Well, it looks like this was just a misunderstanding of the way I believed the `.babelrc` file worked. Happy to close.

**Comment by ntucker** [comment]
When I run babel-cli it works fine - .babelrc or babel.config.js. 

with rollup it's not picking up either

**Comment by Andarist** [comment]
@ntucker could u provide a repository with the issue reproduced?

**Comment by ntucker** [comment]
@Andarist Turns out I was missing the extensions: ['.js', '.ts'] on babel options so babel was just skipping my .ts files due to that.
