### ISSUE TITLE
Issue trying to compile ES6 classes in combination with rollup-plugin-commonjs

### ISSUE THREAD

**Issue by arendjr** [rollup/rollup-plugin-babel#297]
Not sure in which repository I should report this, so I also created https://github.com/rollup/rollup-plugin-commonjs/issues/369

When I use rollup-plugin-commonjs on a CommonJS module that contains an ES6 class that gets transpiled through rollup-plugin-babel, the CommonJS requires() and exports are no longer processed.

Here's a showcase for the issue: https://github.com/arendjr/rollup-commonjs-babel-issue

I had started by asking on StackOverflow (https://stackoverflow.com/questions/54256079/using-rollup-in-combination-with-babel-and-commonjs-plugins-doesnt-resolve-all), but I'm now convinced this is an issue, so I'm reporting here as well.

**Comment by Andarist** [comment]
Babel parses files by default as "module", it therefore inserts `import` statement to your code to reference babel helpers here:
https://github.com/rollup/rollup-plugin-babel/blob/66f2f41fb8055dc7ddd8ad28362efbf1f03e72ed/src/helperPlugin.js#L17

Later commonjs plugin parses your code to decide if it's a module or if it's a script and it decides it's a module (because it has import statement inserted by babel) and it skips `require` call rewriting.

I'm not sure how to fix your case reliably in either plugin, why do you want to `require`s instead of import/export syntax? Are we talking about transpiling external dependencies here?

**Comment by arendjr** [comment]
The requires are there because I want to migrate a rather large existing codebase from Browserify to Rollup. I do want to move toward `import` statements, but I thought it'd be a good first step to get everything to work without doing a lot of code rewrites off the bad, which I thought is what the CommonJS plugin is supposed to handle.

Why does the CommonJS plugin skip ES modules, btw? Because if I understand correctly then, that would also mean any modules with mixed imports/requires won't work, right? I can migrate most requires with a codemod, but migrating the require calls that are dispersed throughout the code will be quite the work still, so I had hoped I could do that gradually.

**Comment by Andarist** [comment]
> Because if I understand correctly then, that would also mean any modules with mixed imports/requires won't work, right?

Yeah, they wont work. Its rather not a good idea to mix those 2 - in module world `require` is as good as any other identifier, its not reserved for CJS module format anyhow, so I guess that this plugin assumes it doesnt have to rewrite those because they might be something else. 

It should be possible to set `sourceType: 'unambiguous'` - https://babeljs.io/docs/en/options#sourcetype as babel option. In theory this should solve your problem.

**Comment by arendjr** [comment]
Thanks, that helps me along a bit, indeed!

I think this settles it from the side of the Babel plugin for me, so I'll close it. I'm not sure about the other one though, I kinda feel the CommonJS plugin should at least provide the option to still do its job even when it thinks something is an ES module, so I'll leave a reply there.
