### ISSUE TITLE
presets question

### ISSUE THREAD

**Issue by aeosynth** [rollup/rollup-plugin-babel#3]
if i use the es2015-rollup preset, then i can't run `import {rollup} from 'rollup'`, because nodejs doesn't support es6 modules. do i have to compile and run my build script using two different presets?

**Comment by Rich-Harris** [comment]
Ack. I suspect that might be the case. You could pass the config direct to the plugin, rather than relying on `.babelrc`, though I realise that's not ideal. (Btw don't pass config directly *and* have a `.babelrc` file – the two sets of configuration get merged, the plugins get duplicated, and the end result is total garbage.)

Personally I'm sticking with Babel 5 as it avoids headaches like these, and loads considerably faster.

**Comment by Rich-Harris** [comment]
Correct Babel 6 solution, for anyone finding their way here:

* Have a `.babelrc` file at the root of your project, for use with build tools etc. This will probably have the `es2015` preset
* Create a separate `src/.babelrc` file (assuming your source code is in `src`), with the `es2015-rollup` preset along with any other plugins you need
* If necessary, you can also create a `test/.babelrc` file as appropriate

Babel uses the config from the nearest `.babelrc` file to the file that it's transpiling, which is why this works.

**Comment by mesqueeb** [comment]
@Rich-Harris 
I have a problem where I need Rollup to specify a `.babelrc` file inside a `build` dir. Not the nearest `.babelrc` file to the file it's transpiring, as this causes issues in my setup.

Can I specify a `.babelrc` file inside a specific folder?
