### ISSUE TITLE
Transform on chunk level instead of module level

### ISSUE THREAD

**Issue by sormy** [rollup/rollup-plugin-babel#303]
Would you be open to accept PR that introduces new option to run babel also on chunk level using rollup `renderChunk` hook? 

With current implementation this plugin can't transform some wrapping code that could be added by plugins and rollup itself. 

Processing  using `renderChunk` hook (chuck level) instead of default `transform` (module level) can bring support for targets that are not officially supported by rollup (IE7 for example).

**Comment by Andarist** [comment]
Sure thing, I could consider it - I'm not up to all recent stuff regarding rollup plugin hooks though. Could you describe shortly difference between transform (used one) and renderChunk? Is transform just run per file and renderChunk for concatenated chunks?

**Comment by sormy** [comment]
Transform runs per file and doesn't include rollup glue code our auto-generated wrappers. That is causing that babel can't transform rollup glue code that could be incompatible with target system. If babel could run once on result file it could be better because everything (including glue code) will be processed at once, helpers will be emitted once etc...

**Comment by Andarist** [comment]
It makes potential transform caching harder as the cached values would be invalidated way more often. 

@lukastaegert what would the best way to transform generated code wrappers right now? Maybe it would be possible to add a hook for that?

**Comment by lukastaegert** [comment]
I do not think just transforming the wrapper code alone would be easy as it is usually two blocks of code at beginning and end that are connect e.g. because it is two parts of a function. I personally think there might be room for both. Running babel in renderChunk would be slower for development but Rollup heuristics tend to work better on untranspiled code.

**Comment by Andarist** [comment]
> I do not think just transforming the wrapper code alone would be easy as it is usually two blocks of code at beginning and end that are connect e.g. because it is two parts of a function.

It could work on template-like code - consider IIFE closure wrapper:
```js
(() => {
  ROLLUP_CHUNK;
})();
```
where `ROLLUP_CHUNK` would be inlined after the transformation.

> Running babel in renderChunk would be slower for development but Rollup heuristics tend to work better on untranspiled code.

Often~ babel is used to transpile syntax which rollup is not able to understand on its own, so just moving to renderChunk from transform is unfortunately not an option (even if only in prod env).

**Comment by lukastaegert** [comment]
I see those points, I am just not sure if a transformer for Rollup's wrapper code is a good way forward, also with other planned developments in mind. I think for the issue at hand, performance might not be an issue as it is probably not necessary for development.

What I would suggest is that it is possible to run Babel with an option to transform the generated chunks instead of the input modules. Then in a hypothetical scenario, I would add the Babel plugin twice, once without this option and all base transformations I need such as transpile JSX, and once with this flag that does any remaining legacy transformations.

This might become more interesting as there are ideas to have per-output plugins that would only do things like renderChunk transformations. In such a scenario, you could have a common build with your basic Babel transformations and generate several outputs, only one of which would receive the additional legacy transformations. I believe this could become a not too uncommon scenario.

**Comment by lukastaegert** [comment]
This is also important as Rollup ditched its legacy option for IE8 support—a controversial move that I myself have still mixed feelings about but unfortunately we do not have a good testing infrastructure to do the IMO necessary browser tests. The legacy option mostly changed some things in the wrapper code but there were also some bits about namespaces that were changed I believe. Having the option to run Babel as a post-processing step could restore IE8 support (or earlier?) for the few who still need it.

**Comment by lukastaegert** [comment]
> Would you be open to accept PR that introduces new option to run babel also on chunk level

@sormy Depending on what @Andarist says my suggestion would be to have an option to run it on the chunk level **instead** of the module level. Maybe that is what you meant, in that case, you could adjust the description of the issue? Technically, it should be possible to have more than one Babel plugin in the pipeline.

**Comment by Andarist** [comment]
> Technically, it should be possible to have more than one Babel plugin in the pipeline.

Yeah, that's totally possible. I've also thought about this double-babel approach - I guess it's the easiest way of moving forward. 

@sormy as @lukastaegert has proposed - this would have to be an option, not a default. I don't have time personally to implement this, so any help would be appreciated. I would advise to hold off a little bit though - I'm planning to revive and land #292 soon, so to avoid merge conflicts it would be easier to start once this happens.

**Comment by chrisfinch** [comment]
I'm having exactly this problem at the moment - a plugin that I am using `rollup-plugin-off-main-thread` adds some wrapper code that is not transformed with babel and breaks my build - is there any temporary fix I could add?

**Comment by sormy** [comment]
Fixed the description of the issue. It could be great to have a `rollup` core feature to choose if wrapper code should be also transformed but until it is implemented we could create an option to opt in into babel transform on chunk level.

**Comment by lukastaegert** [comment]
Just a note that I am still very interested in this. At the moment, I am working on a rollup feature to allow specifying per-output plugins, for which this feature would be an awesome fit. If someone wants to pick this up, ideally it would work in a way that if you specify the option to run it in renderChunk, then the plugin would only expose hooks that are triggered per output as only those will be run in that mode. If you need access to input options, I plan to add them as an argument to the renderStart hook

**Comment by Andarist** [comment]
@lukastaegert I'm not sure what's the course of action here. You have a feature in the works right now that could help this particular problem here, right? How one can pick this up right now (when the feature is still under development)?

**Comment by lukastaegert** [comment]
No, I have a feature in the works that would make this more useful, but even without the feature this would be useful today. There is no need to wait for it, and there should be no dependency on the new feature.

Basically what I am working on is that you can have `plugins` not only as an input option but also as an output option.

Imagine producing several outputs that do not only have different formats but also one that is transpiled to ES5 and an untranspiled one (or one that is minified while the others are not etc.).

Output plugins will have the very same API as normal plugins. But for technical reasons, only output specific hooks will be run on them, which is why you will get a warning if the plugin exposes other hooks such as a `resolveId`, `load` or `transform` hook.

As for this plugin, these hooks should not be exposed when configuring it to be run during renderChunk. As the first two are only used for the Babel helpers, I guess this is not a problem if it is possible to run Babel so that they are injected into every chunk.

**Comment by lukastaegert** [comment]
I have started some preliminary work on this. I hope to be able to prepare a draft PR for further discussion of the details in the next days.

**Comment by lukastaegert** [comment]
Feature at #333, feedback welcome!
