### ISSUE TITLE
Babel helpers are bundled into the output file.

### ISSUE THREAD

**Issue by adolt** [rollup/rollup-plugin-babel#322]
rollup.config.js
<img width="346" alt="image" src="https://user-images.githubusercontent.com/25565814/63256027-5aca9c00-c2a9-11e9-8f2c-f7cc074d7bb0.png">

If I add `@babel/runtime-corejs3` as a dependency. Babel helpers are bundled in, without any `import`.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/25565814/63256464-34f1c700-c2aa-11e9-8171-82999fc62a5a.png">

But when I remove `@babel/runtime-corejs3` from the dependencies, output file looks like this
<img width="865" alt="image" src="https://user-images.githubusercontent.com/25565814/63256590-6f5b6400-c2aa-11e9-967f-9529e13ef319.png">

Same config, different outputs. I tried to add `@babel/runtime-corejs3` to the rollup `external` field, but had no difference.

Could someone explain this? Thanks!

**Comment by Andarist** [comment]
> Same config, different outputs.

I suspect that you could see some warnings about rollup's inability to resolve `@babel/runtime-corejs3` when you hadn't it installed.

> I tried to add @babel/runtime-corejs3 to the rollup external field, but had no difference.

That's because those imports are using "deep paths". With `@babel/runtime-corejs3` added to external you have only added literally `@babel/runtime-corejs3` to externals, not its subdirectories etc. I personally deal with this problem like [this](https://github.com/andreypopp/react-textarea-autosize/blob/efc9bc8e843825038fa1c3e7b8e221b6c673b463/rollup.config.js#L14-L20).

Also - `runtimeHelpers` & `externalHelpers` arent supposed to be used together. You should use only one of them.

**Comment by adolt** [comment]
Appreciate to your reply.

> I suspect that you could see some warnings about rollup's inability to resolve @babel/runtime-corejs3 when you hadn't it installed.

Yes, there are some warnings actually. So, can I say that missing the `corejs3` dependency cause the output difference?

>  I personally deal with this problem like this.
Also - runtimeHelpers & externalHelpers arent supposed to be used together. 

Thanks. I've updated my rollup config like this, and worked as I expected.

**Comment by adolt** [comment]
But there comes another problem. When I import my bundled `iife`-format file to one project, it throws an error while executing.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/25565814/63263046-1e536c00-c2ba-11e9-838c-ada8ba92d0e1.png">


rollup.config.js
<img width="427" alt="image" src="https://user-images.githubusercontent.com/25565814/63262959-ee0bcd80-c2b9-11e9-84e7-9b551b54a9fc.png">

Could you please give me some hints?

**Comment by Andarist** [comment]
I dont actually see where is used before its value is assigned. To get more help regarding this you'd have to share a repository with the issue reproduced in it - without this it's guesswork.

**Comment by adolt** [comment]
Very appreciate to your patience. I've created a [repo](https://github.com/adolt/rollup-babel-issue). Hope this will not take you too much time. Thanks!

**Comment by Andarist** [comment]
The problem for sure is not in this plugin because it's sole responsibility is to transform single files with Babel. The issue ain't that easy to track down BUT my best guess is that `rollup-plugin-commonjs` fails to convert core-js properly (or rather it doesn't handle circular dependencies well, as core-js seems to have a TON of them). I would suggest reporting it over there.

**Comment by adolt** [comment]
Got it. Thanks a lot!

**Comment by adolt** [comment]
@Andarist  Thanks for you help. I modified my `rollup.config.js` like #254 mentioned, and the problem solved.
