### ISSUE TITLE
how use babel/ployfill with rollup

### ISSUE THREAD

**Issue by avivijiang** [rollup/rollup-plugin-babel#328]
In webpack ,we can write [ 'babel-polyfill', 'public/bundle.js' ] in entry option,but rollup ould not resolve entry module (babel-polyfill).

**Comment by Andarist** [comment]
Going to close this now, because I'm cleaning the issues to migrate this plugin to Rollup plugins monorepo ( https://github.com/rollup/plugins ). Hope you understand.

This doesn't mean that I won't respond back if you answer back to me. I'm here to help you - sorry that I couldn't get to you sooner though. 

So going back to topic - I think `babel-polyfill` is CJS only module with highly dynamic content and to make it work with Rollup you'd also have to use `rollup-plugin-commonjs` in your config.
