### ISSUE TITLE
configFile option does not work

### ISSUE THREAD

**Issue by milobluebell** [rollup/rollup-plugin-babel#350]
i have figured out the config file,but it does not work:
```
      babel({
        babelrc: false,
        exclude: /node_modules/,
        runtimeHelpers: true,
        configFile: './babel.config.js',
      }),
```
babel.config.js isn't the config file of rollup babel , why and how to fix it? ty.

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

Once you do that please open a new issue at https://github.com/rollup/plugins because we've migrated this plugin there.
