### ISSUE TITLE
bundle requires core-js internals

### ISSUE THREAD

**Issue by johannes-z** [rollup/rollup-plugin-babel#361]
My final bundle has a lot of statements like the following, even though I'm using `@rollup/plugin-node-resolve` and `@rollup/plugin-commonjs`:

```js
var $ = require('../internals/export')

var isObject = require('../internals/is-object');

var isArray = require('../internals/is-array');
```

I've created a repro here: https://github.com/johannes-z/rollup-babel-yarn
This is the bundle generated: https://github.com/johannes-z/rollup-babel-yarn/blob/master/packages/consumer/lib/main.js

For babel I'm using `@babel/preset-env` with `useBuiltIns: 'usage'`, so that `Promise` gets polyfilled as well.

Ref: https://github.com/rollup/rollup-plugin-babel/issues/312

**Comment by nicolo-ribaudo** [comment]
It's because in `packages/consumer/rollup.config.js` you are only excluding `consumer`'s `node_module`s, but `core-js` comes from the top-level `node_modules`. For this reason, Babel injects imports to `core-js` in `core-js` itself, causing problems.

You can fix it by using `exclude: /node_modules/`, which will ignore all the `node_modules` folders.

**Comment by johannes-z** [comment]
Thanks, that was it.
