### ISSUE TITLE
Exception: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup-plugin-babel#37]
Here is a gist with the relevant information:

https://gist.github.com/Pauan/04b3735d48a978f7b7ec

* `main.js` is the entry point.
* `foo.js` is the file demonstrating the problem.
* `stderr` is the error message + stack trace.

Interestingly, this only happens in this very specific situation:

* The default export is a `=>` function.

* The `=>` function's body contains an object which contains a property with the same name as the function's parameter.

* The property's value is a function which uses the parameter.

**Comment by Rich-Harris** [comment]
As far as I can tell, this is a bug in Babel – if you just transpile `foo.js`, you get the following nonsensical result:

```js
(function (_foo) {
  return {
    foo: function foo() {
      _foo();
    }
  };
});

export {};
```

[Here's the gist.](https://gist.github.com/Rich-Harris/6a7b97f638185737b375)

As far as Rollup is concerned the error comes from the inability to handle `export {}` (it assumes you either have specifiers, or it's a declaration).

Workaround until it gets fixed in Babel would be to assign it to a variable and export that:

```js
var x = (foo) => {
  return {
    foo: function () {
      foo();
    }
  };
};

export default x;
```

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/rollup/rollup/issues/486, since the bug isn't in this plugin

**Comment by Pauan** [comment]
You're right, it does seem like a bug in Babel.

It works in the online Babel REPL (which uses Babel 5), so it appears to be a regression in Babel 6.
