### ISSUE TITLE
unexpected result after a rollup task: native arguments variable is "overscoped"

### ISSUE THREAD

**Issue by tnga** [rollup/rollup-plugin-babel#75]
reporting issue  rollup/rollup#848. take it a look for more informations.

**Comment by Andarist** [comment]
Closing this as outdated and not actionable because it seems like it should be reported in babel itself. This repo contains a rollup plugin that just runs babel transforms over files, it doesn't specify what transforms are ran and it doesn't have anything to do with what transforms actually do. Feel free to open new issue.
