### ISSUE TITLE
Issue with inheritance & unwanted child classes

### ISSUE THREAD

**Issue by qwghlm** [rollup/rollup-plugin-babel#93]
Many thanks for writing this plugin! I've noticed an issue if you are importing a module where there are more than one child classes all sharing same parent and you only want to import one of them. e.g. Take a library `classes.js`:

```
class Animal {
    constructor() {
    }
}

class Cat extends Animal {
    call() {
        console.log("Miaow!")
    }}

class Dog extends Animal {
    call() {
        console.log("Woof!")
    }
}

class Plant {
    constructor() {
    }
}

export { Animal, Cat, Dog, Plant }
```

And a file `index.js` which imports only `Cat`:

```
import { Cat } from './lib/classes.js';

export default function test() {
    var c = new Cat();
}
```

When building a bundle in ES6 on its own, Rollup correctly imports `Animal` and `Cat` and ignores the others.

The Rollup+Babel ES5 build correctly imports `Animal` and `Cat`, but also imports `Dog` - unnecessarily I think. However the dependency checker is clever enough to leave `Plant` alone, so it's clearly doing some work in this case, but not all of it.

Source code & full demo for this issue is here: https://github.com/qwghlm/rolluptest

Is this the expected behaviour for Rollup+Babel and converting to ES5, or am I correct in thinking this is a bug?

**Comment by Andarist** [comment]
The most likely issue here is that babel transforms classes into IIFES, it's really hard for rollup (and other tools) to tree-shake those, because tools are unsure if it's safe to drop them - IIFE might contain some relevant side effects that you would expect to be preserved (in this case of course you dont, but a tool cannot know that). Issues such as this and others (i.e. static properties) are known to prevent tree-shaking in most cases.

Anyway - it's rollup issue more than anything else and not this particular plugin's fault.
